{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ $.Values.namespace }}
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          env:
            # один брокер = один и контроллер, id = 1
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "controller,broker"

            # KRaft
            - name: KAFKA_CLUSTER_ID
              value: {{ .Values.kafka.clusterId | quote }}
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka.{{ $.Values.namespace }}.svc:{{ .Values.kafka.controllerPort }}"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            # слушаем внутри pod’а и наружу через сервис
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:{{ .Values.kafka.servicePort }},CONTROLLER://:{{ .Values.kafka.controllerPort }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.{{ $.Values.namespace }}.svc:{{ .Values.kafka.servicePort }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

          ports:
            - containerPort: {{ .Values.kafka.servicePort }}
            - containerPort: {{ .Values.kafka.controllerPort }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
      volumes:
        # для dev можно пустой emptyDir (данные пропадут при пересоздании pod’а)
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ $.Values.namespace }}
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: {{ .Values.kafka.servicePort }}
      targetPort: {{ .Values.kafka.servicePort }}
{{- end }}
