{{- if .Values.kafka.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: {{ .Values.kafka.service.port }}
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ $.Values.namespace }}
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - containerPort: 9092
          # Основной трюк: форматируем storage и сразу запускаем брокер
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Полные пути к скриптам Kafka
              KAFKA_BIN=/opt/kafka/bin

              # если лог-директория пустая — форматируем хранилище
              if [ ! -f /var/lib/kafka/data/meta.properties ]; then
                KAFKA_CLUSTER_ID="$(${KAFKA_BIN}/kafka-storage.sh random-uuid)"
                ${KAFKA_BIN}/kafka-storage.sh format \
                  -t "${KAFKA_CLUSTER_ID}" \
                  -c /opt/kafka/config/kraft/server.properties
              fi

              # запускаем брокер в KRaft
              exec ${KAFKA_BIN}/kafka-server-start.sh /opt/kafka/config/kraft/server.properties

          volumeMounts:
            - name: kafka-data
              mountPath: {{ .Values.kafka.logDir }}
      volumes:
        - name: kafka-data
          emptyDir: { }
{{- end }}
