image:
  repository: your-registry/rhythmix-core-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  className: traefik
  path: /
  tls:
    enabled: false
    secretName: ""

replicaCount: 1

resources: { }

serviceAccount:
  create: true
  name: rhythmix-core-sa

vault:
  enabled: false
  role: "rhythmix-backend"
  paths:
    postgres: "secret/data/rhythmix/dev/postgres"
    minio: "secret/data/rhythmix/dev/minio"
    kafka: "secret/data/rhythmix/dev/kafka"
    keycloak: "secret/data/rhythmix/dev/keycloak"

env:
  SPRING_PROFILES_ACTIVE: "default"
