namespace: rhythmix-dev

image:
  repository: sh2rman/rhythmix-core-service
  tag: "6662093338ee21e2fa2f49adb0e39d9665950c0c"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: rhythmix-core-dev.sh-2rm-an.tech
  path: /
  tls:
    enabled: false

serviceAccount:
  create: true
  name: rhythmix-backend-sa

vault:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: "dev"

  POSTGRES_URL: "jdbc:postgresql://postgres.rhythmix-dev.svc:5432/rhythmix"
  POSTGRES_USER: "rhythmix"
  POSTGRES_PASSWORD: "rhythmix-dev-pass"

  REDIS_HOST: "redis.rhythmix-dev.svc"
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: "kafka.rhythmix-dev.svc:9092"

  MINIO_URL: "http://minio.rhythmix-dev.svc:9000"
  MINIO_ROOT_USER: "rhythmix-minio"
  MINIO_ROOT_PASSWORD: "rhythmix-minio-dev-pass"

  KEYCLOAK_URL: "http://keycloak.sh-2rm-an.tech/realms/Rhythmix"
