apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: rhythmix
data:
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0:9091,1@kafka-1:9091,2@kafka-2:9091"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_KRAFT_CLUSTER_ID: "PVjHlx7ESeesq55jeB6Efw"
