# ConfigMap для несекретных данных
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: rhythmix
data:
  POSTGRES_DB: Rhythmix
  POSTGRES_USER: db_user

---
# Secret для паролей
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rhythmix
type: Opaque
stringData:
  POSTGRES_PASSWORD: db_password
