namespace: rhythmix-dev

postgres:
  image: postgres:16
  username: rhythmix
  password: rhythmix-dev-pass
  database: rhythmix
  storageSize: 5Gi

redis:
  image: redis:7
  storageSize: 1Gi

minio:
  image: quay.io/minio/minio:latest
  accessKey: rhythmix-minio
  secretKey: rhythmix-minio-dev-pass
  storageSize: 10Gi

kafka:
  enabled: true

  image: "apache/kafka:3.7.0"

  servicePort: 9092
  controllerPort: 9093

  clusterId: "PVjHlx7ESeesq55jeB6Efw"

