namespace: rhythmix-dev

postgres:
  image: postgres:16
  username: rhythmix
  password: rhythmix-dev-pass
  database: rhythmix
  storageSize: 5Gi

redis:
  image: redis:7
  storageSize: 1Gi

minio:
  image: quay.io/minio/minio:latest
  accessKey: rhythmix-minio
  secretKey: rhythmix-minio-dev-pass
  storageSize: 10Gi

kafka:
  enabled: true

  image:
    repository: apache/kafka
    tag: "3.7.0"
    pullPolicy: IfNotPresent

  service:
    name: kafka
    port: 9092

  kraft:
    clusterId: "4L6g3nShT-eMCtK--X86sw"
