namespace: rhythmix-dev

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.2.5"
  pullPolicy: Always

replicaCount: 1

postgres:
  host: postgres.rhythmix-dev.svc
  port: 5432
  db: rhythmix
  user: rhythmix
  password: rhythmix-dev-pass

kafka:
  # наш сервис kafka в кластере (порт 9090 из infra-чарта)
  bootstrapServers: "kafka.rhythmix-dev.svc:9090"

service:
  name: keycloak
  port: 8080

admin:
  username: admin
  password: admin-dev-pass

ingress:
  enabled: true
  className: "traefik"            # для k3s traefik обычно норм
  host: keycloak.sh-2rm-an.tech   # можешь поменять на что хочешь
  tls:
    enabled: false                # пока без TLS, потом прикрутим cert-manager
    secretName: keycloak-tls

