apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: rhythmix
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9091
              name: controller
          env:
            # Берём индекс пода из HOSTNAME (kafka-0, kafka-1, kafka-2)
            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_PROCESS_ROLES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_PROCESS_ROLES
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9091
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://${HOSTNAME}.kafka.rhythmix.svc.cluster.local:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_KRAFT_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_KRAFT_CLUSTER_ID

          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
