apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: rhythmix-backend
    app.kubernetes.io/component: backend
