apiVersion: v1
kind: Service
metadata:
  name: rhythmix-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: rhythmix-backend
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: rhythmix-backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
