events {}

http {

   server {
       listen 80;
       server_name keycloak.lan;

       location / {
           proxy_pass http://keycloak:8080/;
       }
   }

   server {
       listen 80;
       server_name minio.lan;

       location / {
           proxy_pass http://minio:9000/;
       }
   }

}