events {}

http {

   server {
       listen 80;
       server_name keycloak.local;

       location / {
           proxy_pass http://keycloak:8080/;
       }
   }

   server {
       listen 80;
       server_name minio.local;

       location / {
           proxy_pass http://minio:9000/;
       }
   }

}