apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: rhythmix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: your-docker-repo/spring-app:latest
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-service:5432/modulate_db"
          - name: SPRING_REDIS_HOST
            value: "redis-service"
        ports:
        - containerPort: 8080